// Code generated by MockGen. DO NOT EDIT.
// Source: token.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITokenStorage is a mock of ITokenStorage interface.
type MockITokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MockITokenStorageMockRecorder
}

// MockITokenStorageMockRecorder is the mock recorder for MockITokenStorage.
type MockITokenStorageMockRecorder struct {
	mock *MockITokenStorage
}

// NewMockITokenStorage creates a new mock instance.
func NewMockITokenStorage(ctrl *gomock.Controller) *MockITokenStorage {
	mock := &MockITokenStorage{ctrl: ctrl}
	mock.recorder = &MockITokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenStorage) EXPECT() *MockITokenStorageMockRecorder {
	return m.recorder
}

// DeleteToken mocks base method.
func (m *MockITokenStorage) DeleteToken(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockITokenStorageMockRecorder) DeleteToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockITokenStorage)(nil).DeleteToken), arg0, arg1)
}

// GetToken mocks base method.
func (m *MockITokenStorage) GetToken(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockITokenStorageMockRecorder) GetToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockITokenStorage)(nil).GetToken), arg0, arg1)
}

// SetToken mocks base method.
func (m *MockITokenStorage) SetToken(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetToken indicates an expected call of SetToken.
func (mr *MockITokenStorageMockRecorder) SetToken(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockITokenStorage)(nil).SetToken), arg0, arg1, arg2)
}
